libwxia: resolve misuse of TWAIN API
A TW_STATUS object is passed as 3rd argument to wxLogDebug,
but don't know how to print this. The format string wanted
an int (%d), too, so give it one.

  CXX      twainbase.lo
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/string.h:46:0,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/memory.h:15,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/object.h:19,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/wx.h:15,
                 from twainbase.cpp:32:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/strvararg.h: In instantiation of 'struct wxFormatStringSpecifier<TW_STATUS>':
/usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/strvararg.h:456:9:   required from 'wxArgNormalizer<T>::wxArgNormalizer(T, const wxFormatString*, unsigned int) [with T = TW_STATUS]'
/usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/strvararg.h:476:47:   required from 'wxArgNormalizerWchar<T>::wxArgNormalizerWchar(T, const wxFormatString*, unsigned int) [with T = TW_STATUS]'
/usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/log.h:968:5:   required from 'void wxLogger::Log(const wxFormatString&, T1, T2) [with T1 = short int; T2 = TW_STATUS]'
twainbase.cpp:362:45:   required from here
/usr/x86_64-w64-mingw32/sys-root/mingw/include/wx-3.0/wx/strvararg.h:354:10: error: 'value' is not a member of 'wxFormatStringSpecifierNonPodType<false>'
     enum { value = wxFormatStringSpecifierNonPodType<is_enum::value>::value };
          ^
Makefile:433: recipe for target 'twainbase.lo' failed
make: *** [twainbase.lo] Error 1